Gemfile, Gemfile.lock, config/environments/production.rb, config/unicorn.rb
=> deploy_unicorn

config/unicorn.rb
=> deploy_watanabe5

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/unicorn.rb
=> auto_deploy

config/deploy.rb
=> basic_auth2

app/assets/stylesheets/_edit.user.scss
ユーザープロフィール画面を編集する
登録後プロフィールを編集しないと、登録後のプロフィール変更が出来ないから
=> ユーザプロフィール編集(微修正)

Gemfile, Gemfile.lock, app/uploaders/image_uploader.rb, config/initializers/carrierwave.rb
=> deploy_S3_1

app/assets/stylesheets/_logout.scss, app/assets/stylesheets/application.scss, app/views/users/logout.html.haml, config/routes.rb
#What
ログアウト画面の実装。
（ログアウト機能をつけるための画面を作成）
#Why
ログアウト機能機能がないとユーザーがログインしたまま、
ログアウトできない状態になるため。
=> ログアウト画面の実装[改訂版]

app/assets/stylesheets/_logout.scss, app/assets/stylesheets/_mypage_aside.scss, app/views/users/_user_aside.html.haml, app/views/users/logout.html.haml
#What
マイページサイドバーの実装
#Why
マイページサイドバーより各詳細ページへ移行するため必要。
=> ユーザーサイドバー画面の実装[改訂版]

app/assets/stylesheets/application.scss, app/assets/stylesheets/new_create.scss, app/controllers/users_controller.rb, app/views/users/new_create.html.haml, config/routes.rb
#what
新規会員登録ページ１ページ目
#what
どの方法で登録するか選択するため
=> [WIP]新規会員登録ページ

app/assets/stylesheets/_top_page_aside_footer.scss
=> top_aside_footer_modify

app/assets/stylesheets/_complete.scss, app/assets/stylesheets/application.scss, app/controllers/users_controller.rb, app/views/users/complete.html.haml, config/routes.rb
=> WIP 完了画面編集1

app/assets/stylesheets/_identification.scss, app/views/users/identification.html.haml
=> 本人情報確認(微修正)

app/views/users/edit.html.haml, app/views/users/identification.html.haml, app/views/users/logout.html.haml, app/views/users/mypage.html.haml
部分テンプレートによる各画面の実装
部分テンプレートを行うため
=> WIP 部分テンプレート

app/assets/stylesheets/_complete.scss, app/views/users/complete.html.haml
=> render_modify3

app/views/users/new_create.html.haml
新規登録画面フッター修正
新規登録画面フッターが乱れていた為
=> 部分テンプレート 新規登録画面フッター変更

app/views/users/login.html.haml
ログイン画面フッター編集
ログイン画面のフッターが乱れていた為
=> ログイン画面フッター編集 

db/migrate/20191225144559_remove_category_from_products.rb, db/schema.rb
=> productsテーブルのint型id削除

app/controllers/concerns/common_actions.rb, app/controllers/products_controller.rb, app/controllers/users_controller.rb
=> [マージ予定]カテゴリ表示修正

db/schema.rb, db/seeds/user.rb
=> user_data1

app/views/products/_header_child.html.haml, app/views/products/_top_header.html.haml
=> top_category_modify2

config/deploy.rb, db/seeds.rb
下記のテーブルにseedデータ投入
ProductCondition・ShippingCharge・ShippingDay・ProdutStatus・ShippingOrigin
=> その他テーブル　初期データの投入

db/migrate/20191228064315_activehash.rb, db/migrate/20191228065123_categoryactivehashes.rb, db/migrate/20191229092432_prefecture.rb, db/schema.rb
=> migrationerror

app/assets/javascripts/category.js, app/assets/stylesheets/_products.create.scss, app/controllers/products_controller.rb, app/views/products/get_category_children.json.jbuilder, app/views/products/get_category_grandchildren.json.jbuilder, app/views/products/new.html.haml, config/routes.rb
商品出品時にカテゴリーを設定できるように設定する
親カテゴリーに対応した子カテゴリーをセレクトボックスに表示する
子カテゴリーに対応した孫カテゴリーをセレクトボックスに表ぞする
出品した商品を分類しやすくするため
=> カテゴリー表示の実装

app/models/category.rb, app/models/product.rb
=> category_asosiation_add

app/views/products/_index-category.html.haml
=> index_modify

app/views/products/_product_details.html.haml
=> show_modify

app/assets/stylesheets/application.scss, app/assets/stylesheets/edit_select.scss, app/assets/stylesheets/pay_finish.scss, app/controllers/products_controller.rb, app/views/products/edit_select.html.haml, app/views/products/pay_finish.html.haml, config/deploy.rb, config/routes.rb
=> display_marge

app/assets/stylesheets/edit_select.scss, app/controllers/products_controller.rb, app/views/products/edit_select.html.haml, config/routes.rb
=> WIP 編集前画面の作成

Gemfile, Gemfile.lock, app/helpers/products_helper.rb
=> [WIP]to_sの利用方法

app/views/users/show.html.haml
=> usermypage_modify

config/routes.rb
=> routes_modify

app/assets/stylesheets/_products.create.scss, app/controllers/products_controller.rb, app/models/product.rb, app/views/products/_error-messages.html.haml, app/views/products/edit.html.haml, app/views/products/new.html.haml, config/locales/ja.yml
#WHAT
商品出品失敗した時のエラーメッセージの表示
#WHY
何を修正したらいいかわかりやすくするため
※商品出品機能はスプリントレビューすみ
https://gyazo.com/1aa4ccb2c7cdea69c06dee6201fc3ffe
=> 商品出品機能・バリデーションエラーメッセージ表示

app/controllers/products_controller.rb, app/controllers/users_controller.rb, app/views/users/show.html.haml
=> 購入ステータスの更新

app/controllers/products_controller.rb, app/views/products/_top_header.html.haml
=> カテゴリー一覧表示修正

app/views/products/_top_header.html.haml, app/views/products/category_list.html.haml
=> カテゴリー一覧 修正3

app/helpers/products_helper.rb
Reverts oyaoya1123/freemarket_sample_58a#154
=> Revert "to_sの利用"

app/controllers/users_controller.rb
=> user_mypage_modify

app/controllers/products_controller.rb
他人の商品の登録・編集・削除をできないように制限
（URL直打ちでアクション動かそうとした時にrootパスに戻る（url_protectを動かす））
def url_protect
@product=Product.find(params[:id])
unless user_signed_in? && @product.ex_user.id==current_user.id
redirect_to products_path
end
end
=> 他人の商品登録・編集・削除のアクセス
